package com.study.web.admin.domain;

import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

import javax.persistence.*;

@Data
@Entity // JPA가 관리하는 Entity임을 명시.
public class Member {

    @Id // PK 맵핑
    @GeneratedValue(strategy = GenerationType.IDENTITY) // <-- 자동 생성임을 명시. (테이블 생성 시 generated by default as identity 로 생성되었음)
    private Long id;

    //@Column(name = username) <-- 실DB의 컬럼명이 다른 경우 명시. <-- 현재는 동일하기 때문에 주석함.
    private String name;
}
